apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brukerflate-innkreving
  namespace: utenlandsadresser
spec:
  ingresses:
    - https://brukerflate-innkreving.intern.dev.nav.no
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi