/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as KravoversiktImport } from './routes/kravoversikt'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const KravoversiktRoute = KravoversiktImport.update({
  id: '/kravoversikt',
  path: '/kravoversikt',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kravoversikt': {
      id: '/kravoversikt'
      path: '/kravoversikt'
      fullPath: '/kravoversikt'
      preLoaderRoute: typeof KravoversiktImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kravoversikt': typeof KravoversiktRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kravoversikt': typeof KravoversiktRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/kravoversikt': typeof KravoversiktRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kravoversikt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kravoversikt'
  id: '__root__' | '/' | '/kravoversikt'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KravoversiktRoute: typeof KravoversiktRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KravoversiktRoute: KravoversiktRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kravoversikt"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kravoversikt": {
      "filePath": "kravoversikt.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
