/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KravoversiktRouteImport } from './routes/kravoversikt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KravoversiktKravdetaljerKravIdRouteImport } from './routes/kravoversikt/kravdetaljer/$kravId'

const KravoversiktRoute = KravoversiktRouteImport.update({
  id: '/kravoversikt',
  path: '/kravoversikt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KravoversiktKravdetaljerKravIdRoute =
  KravoversiktKravdetaljerKravIdRouteImport.update({
    id: '/kravdetaljer/$kravId',
    path: '/kravdetaljer/$kravId',
    getParentRoute: () => KravoversiktRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kravoversikt': typeof KravoversiktRouteWithChildren
  '/kravoversikt/kravdetaljer/$kravId': typeof KravoversiktKravdetaljerKravIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kravoversikt': typeof KravoversiktRouteWithChildren
  '/kravoversikt/kravdetaljer/$kravId': typeof KravoversiktKravdetaljerKravIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kravoversikt': typeof KravoversiktRouteWithChildren
  '/kravoversikt/kravdetaljer/$kravId': typeof KravoversiktKravdetaljerKravIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kravoversikt' | '/kravoversikt/kravdetaljer/$kravId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kravoversikt' | '/kravoversikt/kravdetaljer/$kravId'
  id: '__root__' | '/' | '/kravoversikt' | '/kravoversikt/kravdetaljer/$kravId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KravoversiktRoute: typeof KravoversiktRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kravoversikt': {
      id: '/kravoversikt'
      path: '/kravoversikt'
      fullPath: '/kravoversikt'
      preLoaderRoute: typeof KravoversiktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kravoversikt/kravdetaljer/$kravId': {
      id: '/kravoversikt/kravdetaljer/$kravId'
      path: '/kravdetaljer/$kravId'
      fullPath: '/kravoversikt/kravdetaljer/$kravId'
      preLoaderRoute: typeof KravoversiktKravdetaljerKravIdRouteImport
      parentRoute: typeof KravoversiktRoute
    }
  }
}

interface KravoversiktRouteChildren {
  KravoversiktKravdetaljerKravIdRoute: typeof KravoversiktKravdetaljerKravIdRoute
}

const KravoversiktRouteChildren: KravoversiktRouteChildren = {
  KravoversiktKravdetaljerKravIdRoute: KravoversiktKravdetaljerKravIdRoute,
}

const KravoversiktRouteWithChildren = KravoversiktRoute._addFileChildren(
  KravoversiktRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KravoversiktRoute: KravoversiktRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
