name: Build and deploy
on:
    push:
        branches:
            - main
jobs:
    build_and_push:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          id-token: write
          actions: read
      outputs:
          image: ${{ steps.docker-build-push.outputs.image }}
          telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
      steps:
          - uses: actions/checkout@v5
          - name: Build and push image and SBOM to OCI registry
            uses: nais/docker-build-push@v0
            id: docker-build-push
            with:
                team: utenlandsadresser
                build_secrets: |
                    github_npm_token=${{ secrets.READER_TOKEN }}
                identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    deploy:
        strategy:
            matrix:
                environment: [dev-gcp, prod-gcp]
        needs: build_and_push
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            actions: read
        environment: ${{ matrix.environment }}
        steps:
            - uses: actions/checkout@v5
            - name: Deploy to ${{ matrix.environment }}
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: ${{ matrix.environment }}
                  RESOURCE: .nais/app.yaml
                  WORKLOAD_IMAGE: ${{ needs.build_and_push.outputs.image }}
                  VARS: .nais/vars/${{ matrix.environment }}.yaml
                  TELEMETRY: ${{ needs.build_and_push.outputs.telemetry }}
