name: Build and deploy
on:
    push:
        branches:
            - main
jobs:
    build_and_push:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          id-token: write
          actions: read
      steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0 # Fetch all history for what-changed action
          - name: Determine what to do
            id: changed-files
            uses: "nais/what-changed@main"
            with:
                files: .nais/app.yaml
          - name: Build and push image and SBOM to OCI registry
            if: steps.changed-files.outputs.changed != 'only-inputs'
            uses: nais/docker-build-push@v0
            id: docker-build-push
            with:
                team: utenlandsadresser
                build_secrets: |
                    github_npm_token=${{ secrets.READER_TOKEN }}
    deploy:
        strategy:
            matrix:
                environment: [dev-gcp, prod-gcp]
        needs: build_and_push
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            actions: read
        environment: ${{ matrix.environment }}
        steps:
            - uses: actions/checkout@v5
            - name: Deploy to {{ matrix.environment }}
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: ${{ matrix.environment }}
                  RESOURCE: .nais/app.yaml
                  VAR: "image=${{ needs.build_and_push.outputs.image }}"
                  VARS: ".nais/vars/${{ matrix.environment }}.yaml"
