name: Build and deploy
on:
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        name: Build, push and deploy
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            actions: read
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch all history for what-changed action
            - name: Generate .npmrc file from template
              run: |
                cat .npmrc.template | sed 's/<YOUR_GITHUB_TOKEN>/${{ secrets.READER_TOKEN }}/g' > .npmrc
            - name: Determine what to do
              id: changed-files
              uses: "nais/what-changed@main"
              with:
                  files: .nais/app.yaml
            - name: Build and push image and SBOM to OCI registry
              if: steps.changed-files.outputs.changed != 'only-inputs'
              uses: nais/docker-build-push@v0
              id: docker-build-push
              with:
                  team: utenlandsadresser
                  build_secrets: |
                      npmrc=.npmrc
            - name: Deploy to Nais
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/app.yaml
                  WORKLOAD_IMAGE: ${{ steps.docker-build-push.outputs.image }}
                  TELEMETRY: ${{ steps.docker-build-push.outputs.telemetry }}
